name: CICD

on:
   workflow-dispatch:
jobs:
     code:
       runs-on: Ubuntu-latest
       steps:
         -name: clone the code
          run: echo"cloning the code"
      build:
        runs-on: Ubuntu-latest
        steps:
        -name: Build using docker
         run: echo"Building using docker" 
     test:
       runs-on: Ubuntu-latest
       steps:
         -name: testing the cases
          run: echo "testing the app"    
     deploy:
        runs-on: Ubuntu-latest
        steps:
           -name: deploying on the machine 
            run: echo"deploying the code"
  
