name: Hello

on:
  workflow_dispatch:

jobs:
  say-hello:
    # create an ephemeral container with ubuntu running
    runs-on: ubuntu-latest

    # ephemeral container will have steps to execute
    steps:
      - name: Say hello to everyone
        run: echo "hello Dosto"
